"use client";

/**
 * Turns the page into a PDF using the browser's own print pipeline.
 *
 * Deliberately not a link to a pre-rendered file. A committed PDF is a second
 * copy of the company profile that has to be regenerated by hand every time a
 * service, a case study or a phone number changes — and the first time someone
 * forgets, the document a client is reading disagrees with the site it came
 * from. Printing the live page means there is only ever one profile.
 *
 * The deck block in app/globals.css sets the page box to the slide canvas, so
 * what comes out is one slide per page at the size it was drawn.
 */
export default function PrintButton({
  className = "",
  children,
}: {
  className?: string;
  children: React.ReactNode;
}) {
  return (
    <button type="button" onClick={() => window.print()} className={className}>
      {children}
    </button>
  );
}
